apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: {{ include "raoa.fullname" . }}
spec:
  version: 7.6.0
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  nodeSets:
    - name: data
      count: {{.Values.data.elasticsearch.nodeCount}}
      {{ if .Values.data.elasticsearch.volumesOverride }}
      podTemplate:
        spec:
          volumes:
            {{- toYaml .Values.data.elasticsearch.volumes | nindent 12 }}
      {{ end }}
      config:
        node.master: true
        node.data: true
        node.ingest: true
        xpack.ml.enabled: false

